[programs.localnet]
anchor_escrow = "AHnWUmyXfyRqtN3AwoRxMoyVKskyF9cS59YE2ZbqB8x6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/IE0aP3Ge9OImn-QN6tBCxrkQuWUiH5rP"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.1" # Solana version to use
